export const POPULAR_ROUTES = [
  {
    id: 'route-jfk-lhr',
    from: 'New York',
    fromCode: 'JFK',
    to: 'London',
    toCode: 'LHR',
    pricePerKg: '$6.5',
    rating: 4.9,
    reviews: 4200,
    popular: true,
    bgGradient: 'from-indigo-900 via-blue-800 to-blue-900',
    emoji: '🏙️',
    description: 'NYC to UK — Most popular route',
  },
  {
    id: 'route-cdg-dxb',
    from: 'Paris',
    fromCode: 'CDG',
    to: 'Dubai',
    toCode: 'DXB',
    pricePerKg: '$7.2',
    rating: 4.8,
    reviews: 3100,
    popular: true,
    bgGradient: 'from-amber-900 via-orange-800 to-rose-900',
    emoji: '🗼',
    description: 'France to UAE — High demand',
  },
  {
    id: 'route-sin-syd',
    from: 'Singapore',
    fromCode: 'SIN',
    to: 'Sydney',
    toCode: 'SYD',
    pricePerKg: '$8.1',
    rating: 4.9,
    reviews: 1980,
    popular: true,
    bgGradient: 'from-teal-900 via-cyan-800 to-blue-900',
    emoji: '🌏',
    description: 'SEA to Australia — Trending',
  },
  {
    id: 'route-yyz-lhr',
    from: 'Toronto',
    fromCode: 'YYZ',
    to: 'London',
    toCode: 'LHR',
    pricePerKg: '$6.9',
    rating: 4.7,
    reviews: 1540,
    popular: false,
    bgGradient: 'from-red-900 via-rose-800 to-pink-900',
    emoji: '🍁',
    description: 'Canada to UK — Great value',
  },
];

export const NAV_LINKS = [
  { label: 'How It Works', href: '/how-it-works' },
  { label: 'Services', href: '/services' },
  { label: 'About Us', href: '/about' },
  { label: 'Contact Us', href: '/contact' },
];

export const FOOTER_LINKS = {
  travelers: [
    { label: 'How It Works', href: '/how-it-works' },
    { label: 'Post a Trip', href: '/traveler' },
    { label: 'Trip Dashboard', href: '/trips' },
    { label: 'Earnings', href: '/earnings' },
    { label: 'Traveler Help Center', href: '/support' },
  ],
  senders: [
    { label: 'How It Works', href: '/how-it-works' },
    { label: 'Find a Traveler', href: '/sender' },
    { label: 'My Bookings', href: '/bookings' },
    { label: 'Shipping Guide', href: '/services' },
    { label: 'Sender Help Center', href: '/support' },
  ],
  company: [
    { label: 'About Us', href: '/about' },
    { label: 'Careers', href: '/careers' },
    { label: 'Press', href: '/press' },
    { label: 'Blog', href: '/blog' },
    { label: 'Contact Us', href: '/contact' },
  ],
  support: [
    { label: 'Safety & Security', href: '/safety' },
    { label: 'Escrow Protection', href: '/escrow' },
    { label: 'FAQs', href: '/support' },
    { label: 'Terms of Service', href: '/terms' },
    { label: 'Privacy Policy', href: '/privacy' },
  ],
};
